% This script is written and read by pdetool and should NOT be edited.
% There are two recommended alternatives:
% 1) Export the required variables from pdetool and create a MATLAB script
%    to perform operations on these.
% 2) Define the problem completely using a MATLAB script. See
%    https://www.mathworks.com/help/pde/examples.html for examples
%    of this approach.
function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',9);
set(ax,'DataAspectRatio',[1 1 1]);
set(ax,'PlotBoxAspectRatio',[2 3.5 1]);
set(ax,'XLimMode','auto');
set(ax,'YLimMode','auto');
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pdepoly([ 0,...
 3,...
 4,...
 4,...
 3.5,...
 2,...
 2,...
 3.25,...
 3.5,...
 3.5,...
 0,...
],...
[ 7,...
 7,...
 6,...
 4,...
 4.5,...
 4.5,...
 4,...
 4,...
 3.75,...
 3,...
 3,...
],...
 'Ag');
pdepoly([ 4,...
 4,...
 3.5,...
 2,...
 2,...
 3.25,...
 3.5,...
 3.5,...
],...
[ 0,...
 4,...
 4.5,...
 4.5,...
 4,...
 4,...
 3.75,...
 0,...
],...
 'Cu2');
pderect([0 1 4 4.5],'Cu1');
pderect([0 0.5 4.5 5],'Si');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','Ag+Cu2+Cu1+Si')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(23,...
'neu',...
1,...
'0',...
'0')
pdesetbd(22,...
'neu',...
1,...
'150000000',...
'0')
pdesetbd(21,...
'neu',...
1,...
'0',...
'0')
pdesetbd(20,...
'neu',...
1,...
'0',...
'0')
pdesetbd(13,...
'neu',...
1,...
'0',...
'0')
pdesetbd(9,...
'dir',...
1,...
'1',...
'18')
pdesetbd(8,...
'neu',...
1,...
'0',...
'0')
pdesetbd(4,...
'neu',...
1,...
'0',...
'0')
pdesetbd(3,...
'neu',...
1,...
'0',...
'0')
pdesetbd(2,...
'dir',...
1,...
'1',...
'18')
pdesetbd(1,...
'dir',...
1,...
'1',...
'18')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')

% PDE coefficients:
pdeseteq(1,...
'1.0',...
'1.0',...
'(1.0)+(1.0).*(0.0)',...
'(1.0).*(1.0)',...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['1.0';...
'1.0';...
'1.0';...
'1.0';...
'1.0';...
'0.0'])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('0','1000','10','pdeadworst',...
'0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');
